name: Update disabled.json

on:
  workflow_dispatch:
  push:
    paths:
      - "save.json"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy save.json to disabled.json
        run: cp save.json disabled.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add disabled.json
          git commit -m "Update disabled.json"
          git push
